skin: "/assets/css/skins/light.css"
locale: en-US
title: "nonomino"
description: "This site may or may not guide you to life, the universe and everything."
baseurl:
url: "https://nonomino.is-a.dev"
logo: /assets/images/avatar.jpg
date_format: "%B %-d, %Y"
read_time: true
words_per_minute: 150
exclude: ["Gemfile.lock"]
verbose: false
mathjax: false
search_full_content: true

author:
  name: nonomino
  picture: /assets/images/avatar.jpg
  email: nonomino@perso.be
  motto: here be dragons

liquid:
  error_mode: strict

permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml

kramdown:
  auto_ids          : true
  entity_output     : as_char
  toc_levels        : [1, 2, 3, 4, 5, 6]
  smart_quotes      : lsquo,rsquo,ldquo,rdquo
  input             : GFM
  hard_wrap         : false
  footnote_nr       : 1
  show_warnings     : false

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true

footer_links:
  - title: email
    url: mailto:nonomino@perso.be
    icon: icon mail-out
  - title: Linkedin
    url: https://likedin.com/in/nonomino
    icon: icon linkedin
  - title: GitHub
    url: https://github.com/nonomino
    icon: icon github
  - title: Duolingo
    url: https://duolingo.com/profile/nonominox
    icon: icon duolingo
  - title: Feed
    url: atom.xml
    icon: icon rss
